[general]
import = ["/Users/dougs2021air/.config/alacritty/themes/tomorrow_night.yml"]

[colors]
draw_bold_text_with_bright_colors = false

[font]
size = 12.0

[font.normal]
family = "MesloLGLDZ Nerd Font Mono"
style = "Regular"

[window]
decorations = "full"
startup_mode = "Maximized"
dynamic_title = true
opacity = 0.8
title = "Alacritty"

#[window.dimensions]
#columns = 80
#lines = 40

[window.padding]
x = 10
y = 10
